models:
  - name: "mistral-675b"
    path: "/mistral"
    provider: "vllm"

  - name: "nemotron-3-super-120b"
    path: "/nemotron-3-super-120b"
    provider: "vllm"

  - name: "gpt-oss-120b"
    path: "/gpt-oss-120b"
    provider: "vllm"
  
  - name: "qwen2.5vl:72b"
    path: "/qwen2.5vl-72b"
    provider: "ollama"

  - name: "qwen3-asr-1.7b"
    path: "/qwen3-asr-1.7b"
    provider: "vllm"

  - name: "fish-speech-server"
    path: "/fish-speech-server"
    provider: "vllm"
